### PR TITLE
adds encouraging behavior

### PR DESCRIPTION
**Pull request by samm81**

### CODE REVIEW

**Comment by Quelklef** [comment]
... is this tested

**Comment by Quelklef** [comment]
merged into new branch

**Comment by Quelklef** [comment]
> ... is this tested

it was not

**Comment by Quelklef** [comment]
cool, fixed, merged, deployed

**Comment by Quelklef** [comment]
thanks!

**Comment by samm81** [comment]
> ... is this tested

I couldn't figure out how to run it since there's no readme

**Comment by Quelklef** [comment]
there's one js file; run it

**Pull request merged**
